# Generated by Django 5.0.6 on 2024-06-07 10:39
import json

from django.db import migrations, models, transaction


def deployment_ids_json(apps, schema_editor):
    LtiTool = apps.get_model('lti1p3_tool_config', 'LtiTool')

    with transaction.atomic():
        for tool in LtiTool.objects.all():
            tool.deployment_ids_json = json.loads(tool.deployment_ids)
            tool.save(update_fields=('deployment_ids_json',))


def undo_deployment_ids_json(apps, schema_editor):
    LtiTool = apps.get_model('pylti1p3.contrib.django.lti1p3_tool_config', 'LtiTool')

    with transaction.atomic():
        for tool in LtiTool.objects.all():
            tool.deployment_ids = json.dumps(tool.deployment_ids_json)
            tool.save(update_fields=('deployment_ids',))


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0002_alter_ltitool_id_alter_ltitoolkey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='deployment_ids_json',
            field=models.JSONField(
                default=list,
                help_text='List of Deployment IDs.'
                          'Example: ["test-id-1", "test-id-2", ...]'
                          'Each value is provided by the LTI 1.3 Platform. '
            ),
        ),
        migrations.RunPython(deployment_ids_json, undo_deployment_ids_json),
        migrations.RemoveField(
            model_name='ltitool',
            name='deployment_ids',
        ),
        migrations.RenameField(
            model_name='ltitool',
            old_name='deployment_ids_json',
            new_name='deployment_ids',
        ),
    ]
