# Generated by Django 5.0.6 on 2024-06-07 14:21
import json

from django.db import migrations, models, transaction
from django.db.models import Q


def to_json(apps, schema_editor):
    LtiTool = apps.get_model('lti1p3_tool_config', 'LtiTool')
    LtiToolKey = apps.get_model('lti1p3_tool_config', 'LtiToolKey')

    with transaction.atomic():
        for tool in LtiTool.objects.exclude(Q(key_set=None) | Q(key_set='')):
            tool.key_set_json = json.loads(tool.key_set)
            tool.save(update_fields=('key_set_json',))

        for key in LtiToolKey.objects.exclude(Q(public_jwk=None) | Q(public_jwk='')):
            key.public_jwk_json = json.loads(key.public_jwk)
            key.save(update_fields=('public_jwk_json',))


def undo_json(apps, schema_editor):
    LtiTool = apps.get_model('lti1p3_tool_config', 'LtiTool')
    LtiToolKey = apps.get_model('lti1p3_tool_config', 'LtiToolKey')

    with transaction.atomic():
        for tool in LtiTool.objects.exclude(key_set_json=None):
            tool.key_set = json.dumps(tool.key_set_json)
            tool.save(update_fields=('key_set',))

        for key in LtiToolKey.objects.exclude(public_jwk=None):
            key.public_jwk = json.dumps(key.public_jwk_json)
            key.save(update_fields=('public_jwk',))


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0003_ltitool_deployment_ids_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='key_set_json',
            field=models.JSONField(
                blank=True,
                help_text="In case the platform's JWKS endpoint is somehow unavailable you may paste JWKS here."
                          "Value provided by LTI 1.3 Platform",
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ltitoolkey',
            name='public_jwk_json',
            field=models.JSONField(
                blank=True,
                help_text="Tool's generated Public key (from the field above) presented as JWK.",
                null=True
            ),
        ),
        migrations.RunPython(to_json, undo_json),
        migrations.RemoveField(
            model_name='ltitool',
            name='key_set',
        ),
        migrations.RenameField(
            model_name='ltitool',
            old_name='key_set_json',
            new_name='key_set',
        ),
        migrations.RemoveField(
            model_name='ltitoolkey',
            name='public_jwk',
        ),
        migrations.RenameField(
            model_name='ltitoolkey',
            old_name='public_jwk_json',
            new_name='public_jwk',
        ),

    ]
