# Generated by Django 5.0.6 on 2024-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0004_ltitool_key_set_json_ltitoolkey_public_jwk_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitool',
            name='deployment_ids',
            field=models.JSONField(default=list, help_text='List of Deployment IDs. Example: ["test-id-1", "test-id-2", ...] Each value is provided by the LTI 1.3 Platform. '),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='key_set',
            field=models.JSONField(blank=True, help_text="In case the platform's JWKS endpoint is somehow unavailable you may paste JWKS here. Value provided by LTI 1.3 Platform", null=True),
        ),
    ]
